(()=>{
'use strict';
const L=window.DCMLogic,CFG=window.DCM_CONFIG,STORAGE_KEY='dcm-dashboard-partner-v9-data';let data=loadData();const $=id=>document.getElementById(id);
function clone(x){return JSON.parse(JSON.stringify(x));}
function loadData(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const obj=JSON.parse(raw);if(Array.isArray(obj)&&obj.length)return obj;}}catch(e){}return clone(window.DCM_BASE_DATA||[]);}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function pct(v){return v==null?'—':(v*100).toFixed(1)+'%';}function pp(v){if(v==null||!Number.isFinite(v))return '—';return `${v>=0?'+':''}${(v*100).toFixed(1)}%p`;}
function signedCount(v){return `${v>=0?'+':''}${v.toLocaleString()}처`;}
function signedPct(v){if(v==null||!Number.isFinite(v))return '—';return `${v>=0?'+':''}${(v*100).toFixed(1)}%`;}
function monthLabel(m){if(!m)return '—';const[y,mm]=m.split('-');return `${y}년 ${Number(mm)}월`;}
function statusBadge(s){s=L.normStatus(s);return s?`<span class="badge ${s==='O'?'ok':'bad'}">${s}</span>`:'<span class="badge none">-</span>';}
function months(){return [...new Set(data.map(r=>r.month))].sort(L.monthSort);}function prevMonthOf(cur){const ms=months(),i=ms.indexOf(cur);return i>0?ms[i-1]:null;}
function availableOutlets(){return [...new Set(data.map(r=>r.outlet).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));}
function availableManagers(){return [...new Set(availableOutlets().map(o=>CFG.managerByOutlet[o]).filter(Boolean))];}
function outletsForManager(m){return availableOutlets().filter(o=>m==='전체'||CFG.managerByOutlet[o]===m);}
function refreshSelectors(preserve=true){const oldM=$('manager').value||'전체',oldO=$('outlet').value||'전체',oldMonth=$('month').value;const mgrs=availableManagers();$('manager').innerHTML=['전체',...mgrs].map(x=>`<option>${x}</option>`).join('');$('manager').value=preserve&&['전체',...mgrs].includes(oldM)?oldM:'전체';const outs=outletsForManager($('manager').value);$('outlet').innerHTML=['전체',...outs].map(x=>`<option>${x}</option>`).join('');$('outlet').value=preserve&&['전체',...outs].includes(oldO)?oldO:'전체';const ms=months();$('month').innerHTML=ms.length?ms.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join(''):'<option value="">Excel 업로드 필요</option>';$('month').value=preserve&&ms.includes(oldMonth)?oldMonth:(ms.at(-1)||'');}
function scope(month){return L.filterRecords(data,{month,manager:$('manager').value,outlet:$('outlet').value});}
function render(){const cur=$('month').value,prev=prevMonthOf(cur),curr=scope(cur),prior=prev?scope(prev):[],s=L.summarize(curr),ps=L.summarize(prior),ch=L.compare(prior,curr);$('scopeLabel').textContent=`${$('manager').value} · ${$('outlet').value} · ${monthLabel(cur)}`;
 $('kpiRate').textContent=pct(s.rate);$('kpiRateSub').textContent=s.evaluated?`법인별 평가 ${s.evaluated.toLocaleString()}처 중 연동 O ${s.O.toLocaleString()}처 · O/(O+X)`:'평가 데이터 없음';
 $('kpiEval').textContent=s.X.toLocaleString();$('kpiAbs').textContent=s.needAbsolute.toLocaleString();$('kpiSupply').textContent=s.suppliedAbsolute.toLocaleString();$('kpiEvalSub').textContent='법인별 X 합계 (평가처수)';$('kpiAbsSub').textContent='실사업자번호 기준 연동 필요 절대처수';
 if(prev){const d=s.suppliedAbsolute-ps.suppliedAbsolute,rate=ps.suppliedAbsolute?d/ps.suppliedAbsolute:null;$('kpiSupplySub').textContent=`전월 ${ps.suppliedAbsolute.toLocaleString()}처 → 당월 ${s.suppliedAbsolute.toLocaleString()}처 · ${signedCount(d)} (${signedPct(rate)})`;}else $('kpiSupplySub').textContent='3개 법인 중 하나라도 O/X이면 1처';
 renderEntity(s);renderOutletTable(cur);renderNeeds(curr);renderChanges(prev,cur,ps,s,ch);}
function renderEntity(s){$('entityCards').innerHTML=L.E.map(e=>{const x=s.byEntity[e];return `<div class="entity-card"><div class="entity-name">${e}</div><div class="entity-rate">${pct(x.rate)}</div><div class="meter"><i style="width:${x.rate==null?0:x.rate*100}%"></i></div><div class="mini"><span>O ${x.O.toLocaleString()}</span><span>X ${x.X.toLocaleString()}</span><span>평가 ${(x.O+x.X).toLocaleString()}</span></div></div>`}).join('');}
function renderOutletTable(cur){const manager=$('manager').value,selected=$('outlet').value,outs=outletsForManager(manager).filter(o=>selected==='전체'||o===selected);$('outletBody').innerHTML=outs.map(o=>{const s=L.summarize(L.filterRecords(data,{month:cur,outlet:o}));return `<tr><td>${esc(o)}</td><td>${esc(CFG.managerByOutlet[o])}</td>${L.E.map(e=>`<td>${pct(s.byEntity[e].rate)} <small>(O ${s.byEntity[e].O}/X ${s.byEntity[e].X})</small></td>`).join('')}<td><strong>${pct(s.rate)}</strong><br><small>O ${s.O}/${s.evaluated}</small></td><td>${s.X.toLocaleString()}</td><td><strong>${s.needAbsolute.toLocaleString()}</strong></td><td>${s.suppliedAbsolute.toLocaleString()}</td></tr>`}).join('')||'<tr><td colspan="9" class="empty">데이터가 없습니다.</td></tr>';}
function renderNeeds(curr){const rows=L.needList(curr);$('needCount').textContent=`${new Set(rows.map(r=>r.businessNo)).size.toLocaleString()}처`;$('needBody').innerHTML=rows.map(r=>`<tr><td>${esc(r.outlet)}</td><td>${esc(r.manager)}</td><td class="mono">${esc(r.businessNo)}</td><td>${esc(r.businessName)}</td>${L.E.map(e=>`<td>${statusBadge(r.statuses[e])}</td>`).join('')}<td><strong>${r.xCount}</strong></td></tr>`).join('')||'<tr><td colspan="8" class="empty">연동 필요처가 없습니다.</td></tr>';}
function renderChanges(prev,cur,ps,s,ch){$('changeTitle').textContent=prev?`${monthLabel(prev)} 대비 ${monthLabel(cur)}, 전월 대비 무엇이 달라졌나`:`${monthLabel(cur)} (비교할 이전 월 없음)`;$('changeSub').textContent=prev?`${monthLabel(prev)} → ${monthLabel(cur)} · 현재 필터 기준`:'월별 파일을 추가하면 전월 비교가 자동 생성됩니다.';const delta=(s.rate!=null&&ps.rate!=null)?s.rate-ps.rate:null;$('deltaRate').textContent=pp(delta);$('deltaRate').className='change-value '+(delta==null?'':delta>=0?'positive':'negative');$('x2o').textContent=ch.xToO.length.toLocaleString();$('o2x').textContent=ch.oToX.length.toLocaleString();$('newSupply').textContent=ch.newSupply.length.toLocaleString();$('stopSupply').textContent=ch.stoppedSupply.length.toLocaleString();
 const sd=s.suppliedAbsolute-ps.suppliedAbsolute,sdp=prev&&ps.suppliedAbsolute?sd/ps.suppliedAbsolute:null;$('supplyDelta').textContent=prev?`${signedCount(sd)} / ${signedPct(sdp)}`:'—';$('supplyDelta').className='change-value '+(!prev?'':sd>=0?'positive':'negative');$('supplyDeltaSub').textContent=prev?`${ps.suppliedAbsolute.toLocaleString()}처 → ${s.suppliedAbsolute.toLocaleString()}처`:'이전 월 없음';
 const type=$('changeType').value;let rows=[];if(type==='new')rows=ch.newSupply.map(r=>({kind:'신규 공급',...r,corp:r.entities.map(x=>`${x.outlet!==r.outlet?x.outlet+' / ':''}${x.entity} ${x.status}`).join(' · '),change:'미공급 → O/X',detail:`신규 공급 · ${r.entities.map(x=>`${x.entity} 연동 ${x.status}`).join(' / ')}`}));if(type==='stop')rows=ch.stoppedSupply.map(r=>({kind:'공급 중단',...r,corp:r.entities.map(x=>`${x.outlet!==r.outlet?x.outlet+' / ':''}${x.entity} (기존 ${x.status})`).join(' · '),change:'O/X → 미공급',detail:`공급 중단 · 기존 ${r.entities.map(x=>`${x.entity} 연동 ${x.status}`).join(' / ')}`}));if(type==='x2o')rows=ch.xToO.map(r=>({kind:'X→O 개선',...r,corp:r.entity,change:'X → O',detail:'연동 개선'}));if(type==='o2x')rows=ch.oToX.map(r=>({kind:'O→X 해제',...r,corp:r.entity,change:'O → X',detail:'연동 해제'}));$('changeBody').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.kind)}</strong></td><td>${esc(r.outlet)}</td><td>${esc(r.manager)}</td><td class="mono">${esc(r.businessNo)}</td><td>${esc(r.businessName)}</td><td>${esc(r.corp)}</td><td>${esc(r.change)}</td><td>${esc(r.detail)}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">해당 변동이 없습니다.</td></tr>';$('changeCount').textContent=`${rows.length.toLocaleString()}${type==='new'||type==='stop'?'처':'건'}`;}
function normalizeOutlet(name){const s=String(name??'').trim();if(s.includes('원주'))return '백제약품 원주';if(s.includes('영남'))return '백제약품 영남';if(s.includes('대전'))return '백제약품 대전';if(s.includes('영등포'))return '백제약품 영등포';if(s.includes('인천'))return '인천약품';if(s.includes('복산'))return '복산나이스';if(s.includes('유진'))return '유진약품';if(s.includes('아이팜'))return '아이팜코리아';return s;}
function fileYear(name){const m=String(name).match(/(?:^|\D)(\d{2})(\d{2})(?:\D|$)/);if(m)return 2000+Number(m[1]);const lm=months().at(-1);return lm?Number(lm.slice(0,4)):new Date().getFullYear();}
function bizNo(v){if(v==null)return '';const s=String(v).trim();return s.replace(/\.0$/,'').replace(/\D/g,'')||s;}
async function parseWorkbook(file){if(!window.XLSX)throw new Error('Excel 읽기 라이브러리를 불러오지 못했습니다. 인터넷 연결 또는 사내 방화벽을 확인해 주세요.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),year=fileYear(file.name),out=[];wb.SheetNames.forEach(sh=>{const mm=sh.trim().match(/^(\d{1,2})월$/);if(!mm)return;const aoa=XLSX.utils.sheet_to_json(wb.Sheets[sh],{header:1,defval:null,raw:true});if(!aoa.length)return;const hdr=aoa[0].map(x=>String(x??'').trim()),idx=Object.fromEntries(hdr.map((x,i)=>[x,i]));if(idx['도매상명']==null||idx['실사업자번호']==null||idx['실사업자명']==null)return;const month=`${year}-${String(Number(mm[1])).padStart(2,'0')}`,map=new Map();aoa.slice(1).forEach(row=>{const b=bizNo(row[idx['실사업자번호']]);if(!b)return;const outlet=normalizeOutlet(row[idx['도매상명']]);if(!CFG.managerByOutlet[outlet])return;const key=`${month}|||${outlet}|||${b}`;if(!map.has(key))map.set(key,{month,outlet,manager:CFG.managerByOutlet[outlet],businessNo:b,businessName:String(row[idx['실사업자명']]??'').trim(),statuses:{'대웅제약':null,'대웅바이오':null,'한올바이오':null}});const rec=map.get(key);L.E.forEach(e=>{if(idx[e]==null)return;const v=L.normStatus(row[idx[e]]);if(v)rec.statuses[e]=(rec.statuses[e]&&rec.statuses[e]!==v)?'X':v;});});out.push(...map.values());});return out;}
async function uploadFiles(files){const all=[];for(const f of files)all.push(...await parseWorkbook(f));if(!all.length)throw new Error('인식 가능한 월 시트(예: 8월)와 필수 열을 찾지 못했습니다.');const pairs=new Set(all.map(r=>`${r.month}|||${r.outlet}`));data=data.filter(r=>!pairs.has(`${r.month}|||${r.outlet}`));const map=new Map(data.map(r=>[`${r.month}|||${r.outlet}|||${r.businessNo}`,r]));all.forEach(r=>map.set(`${r.month}|||${r.outlet}|||${r.businessNo}`,r));data=[...map.values()];saveData();refreshSelectors(false);render();const p=[...pairs].map(x=>x.split('|||')).sort();$('uploadMsg').textContent=`업데이트 완료: ${p.map(x=>`${monthLabel(x[0])} ${x[1]}`).join(', ')} · ${all.length.toLocaleString()}처 반영`;}
function downloadCSV(rows,filename){const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function exportNeeds(){const cur=$('month').value,rows=L.needList(scope(cur));downloadCSV([['업체/권역','담당자','실사업자번호','실사업자명',...L.E,'X 평가처수'],...rows.map(r=>[r.outlet,r.manager,r.businessNo,r.businessName,...L.E.map(e=>r.statuses[e]||''),r.xCount])],`연동필요_${cur}.csv`);}
function exportChanges(){const cur=$('month').value,prev=prevMonthOf(cur),ch=L.compare(prev?scope(prev):[],scope(cur)),type=$('changeType').value;let rr=[];if(type==='new')rr=ch.newSupply.map(r=>['신규 공급',r.outlet,r.manager,r.businessNo,r.businessName,r.entities.map(x=>`${x.entity}:${x.status}`).join('|'),'미공급→O/X']);if(type==='stop')rr=ch.stoppedSupply.map(r=>['공급 중단',r.outlet,r.manager,r.businessNo,r.businessName,r.entities.map(x=>`${x.entity}:기존${x.status}`).join('|'),'O/X→미공급']);if(type==='x2o')rr=ch.xToO.map(r=>['X→O 개선',r.outlet,r.manager,r.businessNo,r.businessName,r.entity,'X→O']);if(type==='o2x')rr=ch.oToX.map(r=>['O→X 해제',r.outlet,r.manager,r.businessNo,r.businessName,r.entity,'O→X']);downloadCSV([['구분','업체/권역','담당자','실사업자번호','실사업자명','법인/상태','변화'],...rr],`변동상세_${prev||'없음'}_${cur}.csv`);}
function exportBackup(){const blob=new Blob([JSON.stringify({schemaVersion:CFG.schemaVersion,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='DCM_dashboard_backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function importBackup(file){const fr=new FileReader();fr.onload=()=>{try{const obj=JSON.parse(fr.result);if(!Array.isArray(obj.data))throw 0;data=obj.data;saveData();refreshSelectors(false);render();$('uploadMsg').textContent='JSON 백업을 불러왔습니다.';}catch(e){alert('올바른 DCM 대시보드 백업 JSON이 아닙니다.');}};fr.readAsText(file);}
$('manager').addEventListener('change',()=>{const outs=outletsForManager($('manager').value);$('outlet').innerHTML=['전체',...outs].map(x=>`<option>${x}</option>`).join('');$('outlet').value='전체';render();});$('outlet').addEventListener('change',render);$('month').addEventListener('change',render);$('changeType').addEventListener('change',render);$('fileInput').addEventListener('change',async e=>{try{$('uploadMsg').textContent='파일 분석 중...';await uploadFiles([...e.target.files]);}catch(err){$('uploadMsg').textContent='업로드 실패';alert(err.message||err);}finally{e.target.value='';}});$('resetBtn').addEventListener('click',()=>{if(confirm('이 브라우저에 저장된 업로드 데이터를 모두 초기화할까요?')){data=[];saveData();refreshSelectors(false);render();$('uploadMsg').textContent='업로드 데이터가 초기화되었습니다. 본인 업체 Excel 파일을 다시 선택해 주세요.';}});$('needCsv').addEventListener('click',exportNeeds);$('changeCsv').addEventListener('click',exportChanges);$('backupBtn').addEventListener('click',exportBackup);$('backupInput').addEventListener('change',e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value='';});refreshSelectors(false);render();
})();