(()=>{
'use strict';
const ENDPOINT='https://script.google.com/macros/s/AKfycbygUlCo1x2izUO59cdbbBL3pbGLZgMaGrZz2lrqDfB8m4VtUHC-VqnEJMOeiQOUPXWCuQ/exec';
const L=window.DCMLogic,E=L?.E||['대웅제약','대웅바이오','한올바이오'],TARGET=.95,$=id=>document.getElementById(id);
const reasons={'01':'ERP/시스템 미구축','02':'도입 품목 미연동','03':'전산/데이터 오류','04':'거래처 연동 거부/미협조','05':'공급·거래 중단 예정','06':'신규 거래처 연동 예정','07':'당월 매출 미발생'};
const partnerAliases={baekje:'백제약품',incheon:'인천약품',boksan:'복산나이스',ipharma:'아이팜코리아',yujin:'유진약품'};
let partner='',data=[],actions=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pct=v=>v==null?'—':`${(v*100).toFixed(1)}%`,pp=v=>v==null||!Number.isFinite(v)?'—':`${v>=0?'+':''}${(v*100).toFixed(1)}%p`,key=r=>`${r.outlet}|||${r.businessNo}`;
const monthLabel=m=>{if(!m)return '—';const [y,mm]=m.split('-');return `${y}년 ${Number(mm)}월`;};
const fmtEok=mkrw=>`${(Number(mkrw||0)/100).toLocaleString('ko-KR',{minimumFractionDigits:1,maximumFractionDigits:1})}억`;
function detectPartner(){const q=new URLSearchParams(location.search).get('partner')||'';const d=decodeURIComponent(q).trim();return partnerAliases[d.toLowerCase()]||d||'';}
function partnerOfOutlet(o){const s=String(o||'');if(s.includes('백제'))return '백제약품';if(s.includes('인천'))return '인천약품';if(s.includes('복산'))return '복산나이스';if(s.includes('아이팜')||s.includes('동보'))return '아이팜코리아';if(s.includes('유진'))return '유진약품';return s;}
function actionKey(){return `dcm-partner-master-actions::${partner}`;}
function loadActions(){try{const x=JSON.parse(localStorage.getItem(actionKey()));return Array.isArray(x)?x:[];}catch(e){return [];}}
function saveActions(){localStorage.setItem(actionKey(),JSON.stringify(actions));}
function months(){return [...new Set(data.map(r=>r.month).filter(Boolean))].sort();}
function scope(m){const o=$('outlet').value||'전체';return data.filter(r=>r.month===m&&(o==='전체'||r.outlet===o));}
function prevMonth(cur){const ms=months(),i=ms.indexOf(cur);return i>0?ms[i-1]:null;}
function refreshSelectors(){const outs=[...new Set(data.map(r=>r.outlet).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));$('outlet').innerHTML=['전체',...outs].map(x=>`<option>${esc(x)}</option>`).join('');const ms=months();$('month').innerHTML=ms.length?ms.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join(''):'<option value="">데이터 없음</option>';$('month').value=ms.at(-1)||'';}
function streakRows(cur,curr){const currentKeys=new Set(curr.map(key)),ms=months().filter(m=>m<=cur),by=new Map();data.filter(r=>ms.includes(r.month)).forEach(r=>{const k=key(r);if(!by.has(k))by.set(k,{});by.get(k)[r.month]=r;});const out=[];by.forEach(hist=>{const r=hist[cur];if(!r||!currentKeys.has(key(r)))return;const entityStreak={};let streak=0;E.forEach(e=>{let n=0;for(let i=ms.length-1;i>=0;i--){if(L.normStatus(hist[ms[i]]?.statuses?.[e])==='X')n++;else break;}entityStreak[e]=n;streak=Math.max(streak,n);});out.push({...r,entityStreak,streak});});return out;}
function risks(cur,curr,prior,ch){const pmap=new Map(prior.map(r=>[key(r),r])),o2x=new Set((ch.oToX||[]).map(x=>`${x.outlet}|||${x.businessNo}|||${x.entity}`));return streakRows(cur,curr).filter(r=>E.some(e=>L.normStatus(r.statuses?.[e])==='X')).map(r=>{let score=0,xCount=0;E.forEach(e=>{if(L.normStatus(r.statuses?.[e])!=='X')return;xCount++;score+=2;const st=r.entityStreak[e]||0;if(st>=2)score+=3*Math.min(st-1,3);if(o2x.has(`${r.outlet}|||${r.businessNo}|||${e}`))score+=4;if(!L.normStatus(pmap.get(key(r))?.statuses?.[e]))score+=2;});return {...r,score,xCount,priority:score>=12?'P1':score>=8?'P2':score>=4?'P3':'P4'};}).sort((a,b)=>b.score-a.score||b.xCount-a.xCount||String(a.businessName).localeCompare(String(b.businessName),'ko'));}
function actionFor(r){return actions.find(a=>a.key===key(r))||{};}
function statusLabel(s){return ({TODO:'미조치',IN_PROGRESS:'진행중',WAITING:'회신대기',DONE:'완료'})[s]||'미조치';}
function renderPersist(cur,curr){const rows=streakRows(cur,curr);let pa=0,ps=0,a3=0,a3s=0;rows.forEach(r=>{let hp=false;E.forEach(e=>{if((r.entityStreak[e]||0)>=2){ps++;hp=true;}});if(hp)pa++;if(E.every(e=>L.normStatus(r.statuses?.[e])==='X')){a3++;a3s+=3;}});$('persistAbs').textContent=`${pa}처`;$('persistState').textContent=`${ps}건`;$('all3Abs').textContent=`${a3}처`;$('all3State').textContent=`${a3s}건`;}
function salesSummary(rows){const map=new Map();rows.forEach(r=>{E.forEach(e=>{const st=L.normStatus(r.statuses?.[e]);if(!st)return;const val=Number(r.salesMKRW?.[e]);if(!Number.isFinite(val))return;const k=`${r.month}|||${r.businessNo}|||${e}`;const old=map.get(k);if(!old)map.set(k,{entity:e,status:st,sales:val});else{old.sales=Math.max(old.sales,val);if(old.status!==st)old.status='X';}});});const by={};E.forEach(e=>by[e]={O:0,X:0});let O=0,X=0;map.forEach(x=>{if(x.status==='O'){O+=x.sales;by[x.entity].O+=x.sales;}else if(x.status==='X'){X+=x.sales;by[x.entity].X+=x.sales;}});return {O,X,by};}
function renderSales(curr){const s=salesSummary(curr);$('salesO').textContent=fmtEok(s.O);$('salesX').textContent=fmtEok(s.X);$('salesOSub').textContent=`DW ${fmtEok(s.by['대웅제약'].O)} · BIO ${fmtEok(s.by['대웅바이오'].O)} · HANALL ${fmtEok(s.by['한올바이오'].O)}`;$('salesXSub').textContent=`DW ${fmtEok(s.by['대웅제약'].X)} · BIO ${fmtEok(s.by['대웅바이오'].X)} · HANALL ${fmtEok(s.by['한올바이오'].X)}`;}
function render(){const cur=$('month').value;if(!cur)return renderEmpty();const prev=prevMonth(cur),curr=scope(cur),prior=prev?scope(prev):[],s=L.summarize(curr),ps=L.summarize(prior),ch=L.compare(prior,curr),rr=risks(cur,curr,prior,ch);$('scopeLabel').textContent=`${partner} · ${$('outlet').value} · ${monthLabel(cur)}`;$('rate').textContent=pct(s.rate);$('rate').closest('.kpi').querySelector('small').textContent=`O ${s.O.toLocaleString()}건 / O+X ${s.evaluated.toLocaleString()}건`;$('xCount').textContent=s.X.toLocaleString();$('needCount').textContent=s.needAbsolute.toLocaleString();$('supplyCount').textContent=s.suppliedAbsolute.toLocaleString();renderSales(curr);$('x2o').textContent=(ch.xToO||[]).length.toLocaleString();$('o2x').textContent=(ch.oToX||[]).length.toLocaleString();$('targetNeed').textContent=`${s.evaluated?Math.ceil(Math.max(0,TARGET*s.evaluated-s.O)):0}건`;renderPersist(cur,curr);$('entityCards').innerHTML=E.map(e=>{const x=s.byEntity[e];return `<div class="entity"><h3>${e}</h3><div class="rate">${pct(x.rate)}</div><div class="meter"><i style="width:${x.rate==null?0:x.rate*100}%"></i></div><small>O ${x.O.toLocaleString()} · X ${x.X.toLocaleString()} · 평가 ${(x.O+x.X).toLocaleString()}</small></div>`}).join('');$('changeSub').textContent=prev?`${monthLabel(prev)} → ${monthLabel(cur)}`:'비교할 이전 월이 없습니다.';$('deltaRate').textContent=prev&&s.rate!=null&&ps.rate!=null?pp(s.rate-ps.rate):'—';$('newSupply').textContent=(ch.newSupply||[]).length.toLocaleString();$('stopSupply').textContent=(ch.stoppedSupply||[]).length.toLocaleString();$('changeX2O').textContent=(ch.xToO||[]).length.toLocaleString();renderRisk(rr);renderAction(rr);}
function renderRisk(rr){$('riskTotal').textContent=`X 거래처 ${rr.length.toLocaleString()}처`;$('riskBody').innerHTML=rr.map((r,i)=>`<tr><td>${i+1}</td><td><span class="priority ${r.priority.toLowerCase()}">${r.priority}</span></td><td>${esc(r.outlet)}</td><td>${esc(r.businessName)}</td><td>${esc(r.businessNo)}</td><td>${E.map(e=>L.normStatus(r.statuses?.[e])||'-').join(' / ')}</td><td>${r.streak}개월</td><td><b>${r.score}</b></td></tr>`).join('')||'<tr><td colspan="8" class="empty">X가 있는 거래처가 없습니다.</td></tr>';}
function renderAction(rr){$('actionBody').innerHTML=rr.map(r=>{const a=actionFor(r);return `<tr><td><span class="priority ${r.priority.toLowerCase()}">${r.priority}</span></td><td>${r.score}</td><td>${esc(r.businessName)}</td><td>${esc(r.outlet)}</td><td>${r.streak}개월</td><td><select class="action-field" data-field="reasonCode" data-key="${esc(key(r))}"><option value="">원인 선택</option>${Object.entries(reasons).map(([k,v])=>`<option value="${k}" ${a.reasonCode===k?'selected':''}>${k} ${v}</option>`).join('')}</select></td><td><input class="action-field plan" data-field="plan" data-key="${esc(key(r))}" value="${esc(a.plan||'')}" placeholder="조치계획"></td><td><input class="action-field" type="date" data-field="dueDate" data-key="${esc(key(r))}" value="${esc(a.dueDate||'')}"></td><td><select class="action-field" data-field="status" data-key="${esc(key(r))}">${['TODO','IN_PROGRESS','WAITING','DONE'].map(x=>`<option value="${x}" ${(a.status||'TODO')===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Action 대상이 없습니다.</td></tr>';document.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change',()=>{let a=actions.find(x=>x.key===el.dataset.key);if(!a){const [outlet,businessNo]=el.dataset.key.split('|||');a={key:el.dataset.key,outlet,businessNo};actions.push(a);}a[el.dataset.field]=el.value;a.updatedAt=new Date().toISOString();saveActions();}));}
function renderEmpty(){['rate','xCount','needCount','supplyCount','salesO','salesX','x2o','o2x','targetNeed','deltaRate','newSupply','stopSupply','changeX2O'].forEach(id=>{if($(id))$(id).textContent='-';});['persistAbs','persistState','all3Abs','all3State'].forEach(id=>{if($(id))$(id).textContent='-';});$('riskTotal').textContent='X 거래처 0처';$('riskBody').innerHTML='<tr><td colspan="8" class="empty">표시할 데이터가 없습니다.</td></tr>';$('actionBody').innerHTML='<tr><td colspan="9" class="empty">표시할 데이터가 없습니다.</td></tr>';$('entityCards').innerHTML=E.map(e=>`<div class="entity"><h3>${e}</h3><div class="rate">-</div></div>`).join('');}
async function pull(){try{$('syncMsg').textContent='대웅제약 마스터 데이터 불러오는 중...';$('syncMsg').className='upload-msg';const u=new URL(ENDPOINT);u.searchParams.set('type','dashboard');u.searchParams.set('_',Date.now());const res=await fetch(u,{cache:'no-store'}),json=await res.json();if(!json.ok)throw new Error(json.error||'조회 실패');const all=Array.isArray(json.data)?json.data:[];data=all.filter(r=>partnerOfOutlet(r.outlet)===partner);actions=loadActions();refreshSelectors();render();$('syncMsg').textContent=`마스터 최신 데이터 적용 · ${data.length.toLocaleString()}건 · ${json.updatedAt||''}`;$('syncMsg').className='upload-msg sync-ok';}catch(e){$('syncMsg').textContent=`공용 데이터 연결 실패 · ${e.message}`;$('syncMsg').className='upload-msg sync-error';renderEmpty();}}
function exportActions(){const cur=$('month').value;if(!cur)return;const prev=prevMonth(cur),curr=scope(cur),prior=prev?scope(prev):[],rr=risks(cur,curr,L.compare(prior,curr));const rows=rr.map(r=>{const a=actionFor(r),c=a.reasonCode||'';return {'파트너사':partner,'기준월':cur,'업체/권역':r.outlet,'실사업자번호':r.businessNo,'실사업자명':r.businessName,'Priority':r.priority,'Risk Score':r.score,'Aging':`${r.streak}개월`,'대웅제약':L.normStatus(r.statuses?.['대웅제약'])||'','대웅바이오':L.normStatus(r.statuses?.['대웅바이오'])||'','한올바이오':L.normStatus(r.statuses?.['한올바이오'])||'','원인코드':c,'원인':reasons[c]||'','조치계획':a.plan||'','Due':a.dueDate||'','상태':statusLabel(a.status||'TODO')};});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Action Board');XLSX.writeFile(wb,`DCM_ActionBoard_${partner}_${cur}.xlsx`);}
function start(){partner=detectPartner();$('partnerName').textContent=partner||'업체 링크가 지정되지 않음';if(!partner){$('syncMsg').textContent='URL에 ?partner=백제약품 과 같이 업체를 지정해 주세요.';return;}$('outlet').addEventListener('change',render);$('month').addEventListener('change',render);$('refreshBtn').onclick=pull;$('exportAction').onclick=exportActions;$('exportAction2').onclick=exportActions;$('resetActionBtn').onclick=()=>{if(confirm(`${partner}의 이 브라우저 Action 입력만 초기화할까요?`)){localStorage.removeItem(actionKey());actions=[];render();}};document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth'}));pull();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();