(()=>{
'use strict';
const L=window.DCMLogic,E=L?.E||['대웅제약','대웅바이오','한올바이오'],TARGET=.95;
const $=id=>document.getElementById(id);
const reasons={'01':'ERP/시스템 미구축','02':'도입 품목 미연동','03':'전산/데이터 오류','04':'거래처 연동 거부/미협조','05':'공급·거래 중단 예정','06':'신규 거래처 연동 예정','07':'당월 매출 미발생'};
let currentPartner='',data=[],actions=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pct=v=>v==null?'—':`${(v*100).toFixed(1)}%`;
const pp=v=>v==null||!Number.isFinite(v)?'—':`${v>=0?'+':''}${(v*100).toFixed(1)}%p`;
const key=r=>`${r.outlet}|||${r.businessNo}`;
const monthLabel=m=>{if(!m)return '—';const [y,mm]=m.split('-');return `${y}년 ${Number(mm)}월`;};
const safeName=v=>String(v||'파트너').replace(/[\\/:*?"<>|]/g,'_');
function partnerFromOutlet(name){const s=String(name||'').trim();if(s.includes('백제'))return '백제약품';if(s.includes('인천'))return '인천약품';if(s.includes('복산'))return '복산나이스';if(s.includes('아이팜'))return '아이팜코리아';if(s.includes('유진'))return '유진약품';return s||'미확인 업체';}
function dataKey(p=currentPartner){return `dcm-partner-v2-data::${p}`;}function actionKey(p=currentPartner){return `dcm-partner-v2-actions::${p}`;}
function load(k){try{const x=JSON.parse(localStorage.getItem(k));return Array.isArray(x)?x:[];}catch(e){return [];}}
function save(){if(!currentPartner)return;localStorage.setItem(dataKey(),JSON.stringify(data));localStorage.setItem(actionKey(),JSON.stringify(actions));localStorage.setItem('dcm-partner-v2-last',currentPartner);}
function setPartner(name,loadExisting=true){currentPartner=name||'';$('partnerName').textContent=currentPartner||'Excel 업로드 후 자동 인식';if(loadExisting&&currentPartner){data=load(dataKey());actions=load(actionKey());}refresh(false);render();}
function months(){return [...new Set(data.map(r=>r.month).filter(Boolean))].sort();}
function scope(m){const o=$('outlet').value||'전체';return data.filter(r=>r.month===m&&(o==='전체'||r.outlet===o));}
function prevMonth(cur){const ms=months(),i=ms.indexOf(cur);return i>0?ms[i-1]:null;}
function refresh(preserve=true){const oldO=$('outlet').value||'전체',oldM=$('month').value,outs=[...new Set(data.map(r=>r.outlet).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));$('outlet').innerHTML=['전체',...outs].map(x=>`<option>${esc(x)}</option>`).join('');$('outlet').value=preserve&&['전체',...outs].includes(oldO)?oldO:'전체';const ms=months();$('month').innerHTML=ms.length?ms.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join(''):'<option value="">Excel 업로드 필요</option>';$('month').value=preserve&&ms.includes(oldM)?oldM:(ms.at(-1)||'');}
function statusLabel(s){return ({TODO:'미조치',IN_PROGRESS:'진행중',WAITING:'회신대기',DONE:'완료'})[s]||'미조치';}
function streakRows(cur,curr){const currentKeys=new Set(curr.map(key)),ms=months().filter(m=>m<=cur),by=new Map();data.filter(r=>ms.includes(r.month)).forEach(r=>{const k=key(r);if(!by.has(k))by.set(k,{});by.get(k)[r.month]=r;});const out=[];by.forEach(hist=>{const r=hist[cur];if(!r||!currentKeys.has(key(r)))return;const entityStreak={};let streak=0;E.forEach(e=>{let n=0;for(let i=ms.length-1;i>=0;i--){if(L.normStatus(hist[ms[i]]?.statuses?.[e])==='X')n++;else break;}entityStreak[e]=n;streak=Math.max(streak,n);});out.push({...r,entityStreak,streak});});return out;}
function risks(cur,curr,prior,ch){const pmap=new Map(prior.map(r=>[key(r),r])),o2x=new Set((ch.oToX||[]).map(x=>`${x.outlet}|||${x.businessNo}|||${x.entity}`));return streakRows(cur,curr).filter(r=>E.some(e=>L.normStatus(r.statuses?.[e])==='X')).map(r=>{let score=0,xCount=0;E.forEach(e=>{if(L.normStatus(r.statuses?.[e])!=='X')return;xCount++;score+=2;const st=r.entityStreak[e]||0;if(st>=2)score+=3*Math.min(st-1,3);if(o2x.has(`${r.outlet}|||${r.businessNo}|||${e}`))score+=4;if(!L.normStatus(pmap.get(key(r))?.statuses?.[e]))score+=2;});const priority=score>=12?'P1':score>=8?'P2':score>=4?'P3':'P4';return {...r,score,xCount,priority};}).sort((a,b)=>b.score-a.score||b.xCount-a.xCount||String(a.businessName).localeCompare(String(b.businessName),'ko'));}
function actionFor(r){return actions.find(a=>a.key===key(r))||{};}
function render(){const cur=$('month').value;if(!cur){renderEmpty();return;}const prev=prevMonth(cur),curr=scope(cur),prior=prev?scope(prev):[],s=L.summarize(curr),ps=L.summarize(prior),ch=L.compare(prior,curr),rr=risks(cur,curr,prior,ch);$('scopeLabel').textContent=`${currentPartner} · ${$('outlet').value} · ${monthLabel(cur)}`;$('rate').textContent=pct(s.rate);$('xCount').textContent=s.X.toLocaleString();$('needCount').textContent=s.needAbsolute.toLocaleString();$('supplyCount').textContent=s.suppliedAbsolute.toLocaleString();$('x2o').textContent=(ch.xToO||[]).length.toLocaleString();$('o2x').textContent=(ch.oToX||[]).length.toLocaleString();const persistent=rr.reduce((n,r)=>n+E.filter(e=>(r.entityStreak[e]||0)>=2).length,0);$('persist').textContent=persistent.toLocaleString();const need=s.evaluated?Math.ceil(Math.max(0,TARGET*s.evaluated-s.O)):0;$('targetNeed').textContent=`${need.toLocaleString()}건`;renderEntities(s);renderChanges(prev,s,ps,ch);renderRisk(rr);renderAction(rr);}
function renderEntities(s){$('entityCards').innerHTML=E.map(e=>{const x=s.byEntity[e];return `<div class="entity"><h3>${e}</h3><div class="rate">${pct(x.rate)}</div><div class="meter"><i style="width:${x.rate==null?0:x.rate*100}%"></i></div><small>O ${x.O.toLocaleString()} · X ${x.X.toLocaleString()} · 평가 ${(x.O+x.X).toLocaleString()}</small></div>`;}).join('');}
function renderChanges(prev,s,ps,ch){$('changeSub').textContent=prev?`${monthLabel(prev)} → ${monthLabel($('month').value)}`:'비교할 이전 월이 없습니다.';$('deltaRate').textContent=prev&&s.rate!=null&&ps.rate!=null?pp(s.rate-ps.rate):'—';$('newSupply').textContent=(ch.newSupply||[]).length.toLocaleString();$('stopSupply').textContent=(ch.stoppedSupply||[]).length.toLocaleString();$('changeX2O').textContent=(ch.xToO||[]).length.toLocaleString();}
function renderRisk(rr){$('riskTotal').textContent=`Risk ${rr.length.toLocaleString()}처`;$('riskBody').innerHTML=rr.slice(0,20).map((r,i)=>`<tr><td>${i+1}</td><td><span class="priority ${r.priority.toLowerCase()}">${r.priority}</span></td><td>${esc(r.outlet)}</td><td>${esc(r.businessName)}</td><td>${esc(r.businessNo)}</td><td>${E.map(e=>L.normStatus(r.statuses?.[e])||'-').join(' / ')}</td><td>${r.streak}개월</td><td><b>${r.score}</b></td></tr>`).join('')||'<tr><td colspan="8" class="empty">미연동 위험 거래처가 없습니다.</td></tr>';}
function renderAction(rr){$('actionBody').innerHTML=rr.map(r=>{const a=actionFor(r);return `<tr><td><span class="priority ${r.priority.toLowerCase()}">${r.priority}</span></td><td>${r.score}</td><td>${esc(r.businessName)}</td><td>${esc(r.outlet)}</td><td>${r.streak}개월</td><td><select class="action-field" data-field="reasonCode" data-key="${esc(key(r))}"><option value="">원인 선택</option>${Object.entries(reasons).map(([k,v])=>`<option value="${k}" ${a.reasonCode===k?'selected':''}>${k} ${v}</option>`).join('')}</select></td><td><input class="action-field plan" type="text" data-field="plan" data-key="${esc(key(r))}" value="${esc(a.plan||'')}" placeholder="조치계획"></td><td><input class="action-field" type="date" data-field="dueDate" data-key="${esc(key(r))}" value="${esc(a.dueDate||'')}"></td><td><select class="action-field" data-field="status" data-key="${esc(key(r))}">${['TODO','IN_PROGRESS','WAITING','DONE'].map(x=>`<option value="${x}" ${(a.status||'TODO')===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Action 대상이 없습니다.</td></tr>';document.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change',()=>upsert(el.dataset.key,el.dataset.field,el.value)));}
function upsert(k,field,value){let a=actions.find(x=>x.key===k);if(!a){const [outlet,businessNo]=k.split('|||');a={key:k,outlet,businessNo};actions.push(a);}a[field]=value;a.updatedAt=new Date().toISOString();save();}
function renderEmpty(){['rate','xCount','needCount','supplyCount','x2o','o2x','persist','targetNeed','deltaRate','newSupply','stopSupply','changeX2O'].forEach(id=>{if($(id))$(id).textContent='-';});$('scopeLabel').textContent=currentPartner?`${currentPartner} · 업로드된 데이터 없음`:'Excel 업로드 후 업체명이 자동 인식됩니다.';$('riskTotal').textContent='Risk 0처';$('riskBody').innerHTML='<tr><td colspan="8" class="empty">Excel을 업로드해 주세요.</td></tr>';$('actionBody').innerHTML='<tr><td colspan="9" class="empty">Excel을 업로드해 주세요.</td></tr>';$('entityCards').innerHTML=E.map(e=>`<div class="entity"><h3>${e}</h3><div class="rate">-</div><div class="meter"><i style="width:0"></i></div><small>업로드 데이터 없음</small></div>`).join('');}
function normalizeOutlet(name){return String(name??'').trim();}
function bizNo(v){if(v==null)return '';const s=String(v).trim();return s.replace(/\.0$/,'').replace(/\D/g,'')||s;}
function fileYear(name){const m=String(name).match(/(?:^|\D)(\d{2})(\d{2})(?:\D|$)/);if(m)return 2000+Number(m[1]);const lm=months().at(-1);return lm?Number(lm.slice(0,4)):new Date().getFullYear();}
async function parseWorkbook(file){if(!window.XLSX)throw new Error('Excel 읽기 라이브러리를 불러오지 못했습니다.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),year=fileYear(file.name),out=[];wb.SheetNames.forEach(sh=>{const mm=sh.trim().match(/^(\d{1,2})월$/);if(!mm)return;const aoa=XLSX.utils.sheet_to_json(wb.Sheets[sh],{header:1,defval:null,raw:true});if(!aoa.length)return;const hdr=aoa[0].map(x=>String(x??'').trim()),idx=Object.fromEntries(hdr.map((x,i)=>[x,i]));if(idx['도매상명']==null||idx['실사업자번호']==null||idx['실사업자명']==null)return;const month=`${year}-${String(Number(mm[1])).padStart(2,'0')}`,map=new Map();aoa.slice(1).forEach(row=>{const b=bizNo(row[idx['실사업자번호']]);if(!b)return;const outlet=normalizeOutlet(row[idx['도매상명']]);if(!outlet)return;const k=`${month}|||${outlet}|||${b}`;if(!map.has(k))map.set(k,{month,outlet,businessNo:b,businessName:String(row[idx['실사업자명']]??'').trim(),statuses:{'대웅제약':null,'대웅바이오':null,'한올바이오':null}});const rec=map.get(k);E.forEach(e=>{if(idx[e]==null)return;const v=L.normStatus(row[idx[e]]);if(v)rec.statuses[e]=(rec.statuses[e]&&rec.statuses[e]!==v)?'X':v;});});out.push(...map.values());});return out;}
async function uploadFiles(files){const incoming=[];for(const f of files)incoming.push(...await parseWorkbook(f));if(!incoming.length)throw new Error('인식 가능한 월 시트와 필수 열을 찾지 못했습니다.');const partners=[...new Set(incoming.map(r=>partnerFromOutlet(r.outlet)))];if(partners.length!==1)throw new Error(`서로 다른 업체 데이터가 함께 감지되었습니다: ${partners.join(', ')}. 업체별로 나누어 업로드해 주세요.`);const detected=partners[0];if(currentPartner&&currentPartner!==detected){data=[];actions=[];}currentPartner=detected;$('partnerName').textContent=currentPartner;data=load(dataKey());actions=load(actionKey());const pairs=new Set(incoming.map(r=>`${r.month}|||${r.outlet}`));data=data.filter(r=>!pairs.has(`${r.month}|||${r.outlet}`));const map=new Map(data.map(r=>[`${r.month}|||${r.outlet}|||${r.businessNo}`,r]));incoming.forEach(r=>map.set(`${r.month}|||${r.outlet}|||${r.businessNo}`,r));data=[...map.values()];save();refresh(false);render();$('uploadMsg').textContent=`${currentPartner} 자동 인식 · ${incoming.length.toLocaleString()}처 반영 완료 · 데이터는 이 브라우저에만 저장됩니다.`;}
function exportActions(){const cur=$('month').value;if(!cur)return alert('먼저 Excel을 업로드해 주세요.');const prev=prevMonth(cur),curr=scope(cur),prior=prev?scope(prev):[],ch=L.compare(prior,curr),rr=risks(cur,curr,prior,ch);const rows=rr.map(r=>{const a=actionFor(r),code=a.reasonCode||'';return {'파트너사':currentPartner,'기준월':cur,'업체/권역':r.outlet,'실사업자번호':r.businessNo,'실사업자명':r.businessName,'Priority':r.priority,'Risk Score':r.score,'Aging':`${r.streak}개월`,'대웅제약':L.normStatus(r.statuses?.['대웅제약'])||'','대웅바이오':L.normStatus(r.statuses?.['대웅바이오'])||'','한올바이오':L.normStatus(r.statuses?.['한올바이오'])||'','원인코드':code,'원인':reasons[code]||'','조치계획':a.plan||'','Due':a.dueDate||'','상태':statusLabel(a.status||'TODO'),'마지막수정':a.updatedAt||''};});const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:14},{wch:10},{wch:20},{wch:16},{wch:28},{wch:10},{wch:10},{wch:10},{wch:11},{wch:11},{wch:11},{wch:10},{wch:28},{wch:38},{wch:12},{wch:12},{wch:22}];XLSX.utils.book_append_sheet(wb,ws,'Action Board');const guide=[['DCM Partner Action Board 제출 안내'],['파트너사',currentPartner],['기준월',cur],['제출 절차','Action Board 작성 → Excel 다운로드 → 대웅제약 내부 담당자에게 전달'],['주의','원본 실적 Excel은 포함되지 않습니다. Action Board 조치사항 제출용 파일입니다.']];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(guide),'안내');XLSX.writeFile(wb,`DCM_ActionBoard_${safeName(currentPartner)}_${cur}.xlsx`);}
function backup(){if(!currentPartner)return alert('먼저 Excel을 업로드해 주세요.');const blob=new Blob([JSON.stringify({schemaVersion:2,partner:currentPartner,exportedAt:new Date().toISOString(),data,actions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`DCM_Partner_backup_${safeName(currentPartner)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function restore(file){const fr=new FileReader();fr.onload=()=>{try{const x=JSON.parse(fr.result);if(!Array.isArray(x.data))throw new Error();const p=x.partner||partnerFromOutlet(x.data[0]?.outlet);currentPartner=p;data=x.data;actions=Array.isArray(x.actions)?x.actions:[];$('partnerName').textContent=currentPartner;save();refresh(false);render();$('uploadMsg').textContent=`${currentPartner} 백업을 불러왔습니다.`;}catch(e){alert('올바른 DCM Partner 백업 파일이 아닙니다.');}};fr.readAsText(file);}
function reset(){if(!currentPartner)return;if(!confirm(`${currentPartner}의 이 브라우저 저장 데이터와 Action을 초기화할까요?`))return;localStorage.removeItem(dataKey());localStorage.removeItem(actionKey());data=[];actions=[];refresh(false);render();}
function start(){const last=localStorage.getItem('dcm-partner-v2-last')||'';if(last)setPartner(last,true);else setPartner('',false);$('outlet').addEventListener('change',render);$('month').addEventListener('change',render);$('fileInput').addEventListener('change',async e=>{try{await uploadFiles([...e.target.files]);}catch(err){alert(err.message||'Excel 업로드 중 오류가 발생했습니다.');}e.target.value='';});$('exportAction').onclick=exportActions;$('exportAction2').onclick=exportActions;$('backupBtn').onclick=backup;$('backupInput').addEventListener('change',e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value='';});$('resetBtn').onclick=reset;document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth'}));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();